# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'model_add_delete.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(346, 361)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.AddModel_Button = QtWidgets.QPushButton(self.centralwidget)
        self.AddModel_Button.setObjectName("AddModel_Button")
        self.gridLayout.addWidget(self.AddModel_Button, 1, 0, 1, 1)
        self.DeleteModel_Buttom = QtWidgets.QPushButton(self.centralwidget)
        self.DeleteModel_Buttom.setObjectName("DeleteModel_Buttom")
        self.gridLayout.addWidget(self.DeleteModel_Buttom, 1, 1, 1, 1)
        self.SetAddress = QtWidgets.QPushButton(self.centralwidget)
        self.SetAddress.setObjectName("SetAddress")
        self.gridLayout.addWidget(self.SetAddress, 1, 2, 1, 1)
        self.ListModel = QtWidgets.QListWidget(self.centralwidget)
        self.ListModel.setObjectName("ListModel")
        self.gridLayout.addWidget(self.ListModel, 0, 0, 1, 3)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 346, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.AddModel_Button.setText(_translate("MainWindow", "Add Model"))
        self.DeleteModel_Buttom.setText(_translate("MainWindow", "Delete Model"))
        self.SetAddress.setText(_translate("MainWindow", "Address"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
